Default: &defaults
  user: cabaltest
  password: cabaltest
  host: localhost
  port: 5432
  database: cabaltest
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: cabaltest_test
  <<: *defaults

Staging:
  database: cabaltest_staging
  poolsize: 100
  <<: *defaults

Production:
  database: cabaltest_production
  poolsize: 100
  <<: *defaults
